### ISSUE TITLE
Error after pressing button in menu

### ISSUE THREAD

**Issue by FenixC4** [FabianSchurig/CustomScrews#3]
After pressing the "screw" button this error message appears

![asgasf](https://user-images.githubusercontent.com/43726835/68092624-78ada300-fe8d-11e9-8a90-c526f75c359b.PNG)

**Comment by FenixC4** [comment]
Also after pressing the button when body selected Fusion crashes

**Comment by RZFX** [comment]
Got the same problem :(

**Comment by FabianSchurig** [comment]
Hello @FenixC4 @RZFX
I added the current verion b4e784d as v1.3.0 to the Autodesk store, it should be published soon. Could you check if the error still persists. I had it also in a previous version but now it is gone.

Thank you very much!

**Comment by FenixC4** [comment]
After your update everything is working, i think.
