### ISSUE TITLE
Create screw doesnt show up

### ISSUE THREAD

**Issue by martyymif** [FabianSchurig/CustomScrews#4]
"create screw" doesn't show up under create?
Is this addon still compatible with the latest version of fusion 360?

**Comment by FabianSchurig** [comment]
Hey @martyymif 

if you used the AppStore version then that's true.
You can try my latest commit f36aa0d, it could work.

Thanks!

**Comment by martyymif** [comment]
thanks a lot it works :)

**Comment by RussellTaylor83** [comment]
That has solved it for me. Thank you for this plugin, you have saved my Sunday when no shops are open and I can continue my work! Much appreciated.

**Comment by FabianSchurig** [comment]
Thanks @martyymif and @RussellTaylor83 for your participation!

I submitted the current version b4e784d to Autodesk, there will be an update in the store soon.
![image](https://user-images.githubusercontent.com/11216482/71780253-91872180-2fc0-11ea-8f99-b5251afcfc17.png)

If you have additional Feedback, feel free to message me.
Greets Fabi
