### ISSUE TITLE
Does not run/do anything (on F360 2.0.8412)

### ISSUE THREAD

**Issue by PlasmaHH** [FabianSchurig/CustomScrews#5]
Just downloaded 1.3.0 for F360 2.0.8412 and it doesn't start, hitting the run button in the plugin selection dialogue doesn't do anything. 

Now, not sure if this is a red herring or not (because I don't know which python environment is being used) but when I use the debug functionality, visual studio code opens and lets me run it, and then stops on "import requests" which it can't find. Not sure if this is using F360 python or some other python, and thats the reason it can't find requests. Anyways, as it is not even creating a logfile (which seems to be one of the first things it is attempting) this might lead to something...

I can also try things out, have no idea how this works under F360 though (doing python under linux usually)

**Comment by FabianSchurig** [comment]
@PlasmaHH Thank you very much for your bug-report. I really appreciate your efforts. If you have further information on what changed in Fusion 360 lately or already figured it out you are really welcome to create a PR. Because it is just a hobby project, I can only maintain it in my spare time and it might take me some time to fix it.

In the mean time you could use my other app which has more features. https://github.com/Bitfroest/contentcenter_fusion360

**Comment by PlasmaHH** [comment]
Interestingly autodesk makes it look like the plugin is the official way to make custom threads ...

https://knowledge.autodesk.com/support/fusion-360/troubleshooting/caas/sfdcarticles/sfdcarticles/Custom-Threads-in-Fusion-360.html

They seem to use its existence as an excuse to not provide a dialogue where you can just enter all the values that you could in the xml files...

Anyways as I said I am totally unfamliar with that environment I have no idea where to even start as I get no messages and found no logs with anything...

**Comment by FabianSchurig** [comment]
@PlasmaHH  @fernandex00

Could you please provide the logs, in the file in your users home directory `~/CustomScrews/custom_screws.log`.

**Comment by FabianSchurig** [comment]
https://github.com/Bitfroest/CustomScrews/releases/tag/v1.3.1

Please test it and let me know if you face further problems.

**Comment by fernandex00** [comment]
sorry, just see this a couple of minutes ago, just testing, its working fine
thanks

**Comment by PlasmaHH** [comment]
> @PlasmaHH @fernandex00
> 
> Could you please provide the logs, in the file in your users home directory `~/CustomScrews/custom_screws.log`.

Been on vacation til now. Thing is, I can not because there is none as described earlier. When I get around I will test the new version.
