### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by fernandex00** [FabianSchurig/CustomScrews#6]
i cant make this to work, i tried the autodesk store version and the github version its not working

**Comment by FabianSchurig** [comment]
The same as #5. 

I can look at it next Weekend probably. Please remember me.
Thanks!

**Comment by fernandex00** [comment]
Thanks I'll do it

**Comment by fernandex00** [comment]
Hi, just to remind you, like you said, thank you

**Comment by FabianSchurig** [comment]
https://github.com/Bitfroest/CustomScrews/releases/tag/v1.3.1

Please test it and let me know if you face further problems.
