### ISSUE TITLE
custom thread missing in Create using latest fusion 360

### ISSUE THREAD

**Issue by bill-orange** [FabianSchurig/CustomScrews#9]
I tried installing the addin using the msi install.  It appears normally in the addins pulldown and appears to be running.  However there is no tab in Create.  Did the revision to Fusion360 made recently break it or am I doing something wrong.  This is a Windows 10 environment with a non-commercial license.

**Comment by bill-orange** [comment]
Answered my own question.

**Comment by FabianSchurig** [comment]
Hallo @bill-orange, sorry to hear that you had problems. Did it work at the end?

Best, Fabi

**Comment by bill-orange** [comment]
Yes! It did work in the end. I was looking for the pull-down in Create rather than Insert.

 Unfortunately, it was not helpful for my application.  Astronomy equipment used some odd threads. I suppose there is some weird history behind it but 1.25” eyepieces use a metric thread of 28.5mm x 0.6 pitch. I was looking for a shortcut to create this unusual thread for use in an eyepiece holder. So far I have done it by using 28mm x 1 and 3D printing the part 28.5/28 oversized on X and Y. To correct the pitch, I print Z at 80%. The cumulative pitch error is not a problem in 3 or 4 threads.  

Nice work on the add on.
